# Generated by Django 2.2.5 on 2021-02-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210208_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('em', 'Email'), ('gh', 'GitHub'), ('kk', 'Kakao'), ('emgh', 'Email+GitHub'), ('ghkk', 'GitHub+Kakao'), ('emkk', 'Email+Kakao'), ('emghkk', 'Email+GitHub+Kakao')], default='em', max_length=6),
        ),
    ]
