# Generated by Django 2.2.5 on 2021-03-11 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210311_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birthdate',
            new_name='birthday',
        ),
    ]
