# Generated by Django 2.2.15 on 2021-03-20 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_auto_20201114_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created']},
        ),
    ]
