# Generated by Django 2.2.15 on 2021-03-15 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_auto_20210315_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedday',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_day', to='reservations.Reservation'),
        ),
    ]
