"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from .base_settings import *
from .base_settings import BASE_DIR

import dotenv 

dotenv_path = os.path.join(BASE_DIR, '.env')
if os.path.exists(dotenv_path):
    dotenv.read_dotenv(dotenv=dotenv_path, override=True)

in_production = os.environ.get("IN_PRODUCTION")=="True"
if in_production:
    print("production")
    from .production_settings import *
else:
    from .develop_settings import *
